"""Editorial content. Keep requirements conditional; official authorities decide eligibility."""
SOURCES = {
 'hec': ('HEC — Degree attestation', 'https://www.hec.gov.pk/english/services/students/DAS/Pages/Degree-Attestation.aspx'),
 'ibcc': ('IBCC — Attestation', 'https://ibcc.edu.pk/attestation/'),
 'mofa': ('MOFA Pakistan — Official website', 'https://mofa.gov.pk/'),
 'hcch': ('HCCH — Apostille Convention status and declarations', 'https://www.hcch.net/en/instruments/conventions/status-table/?cid=41'),
 'navttc': ('NAVTTC — Official programmes and portals', 'https://navttc.gov.pk/'),
 'dgip': ('DGIP — Passport services', 'https://www.dgip.gov.pk/'),
 'nadra': ('NADRA — Identity services', 'https://www.nadra.gov.pk/'),
 'uae': ('UAE Ministry of Foreign Affairs — Document attestation', 'https://www.mofa.gov.ae/en/Services/attestation'),
 'saudi': ('Saudi Ministry of Foreign Affairs', 'https://www.mofa.gov.sa/en/'),
}
SERVICES = [
 dict(slug='hec-attestation',symbol='HEC',title='Degree Attestation Assistance',desc='Understand HEC requirements, submission options and common degree-related issues.',audience='Graduates preparing a university degree or transcript for international use.',answer='Start with the qualification, issuing institution and academic record. HEC determines whether a higher-education document is eligible for its attestation service.',steps=['Identify the qualification, awarding institution and campus.','Compare the degree, transcript and identity records before applying.','Use HEC’s current official application instructions and resolve any queries.','Confirm any further authentication with the organisation receiving your document.'],check='An attestation is not an equivalence decision or a promise of acceptance by an employer. Submission formats and verification arrangements must be checked on the current HEC portal.',sources=['hec'],related=['/documents/degree/','/problems/degree-passport-name-mismatch/','/guides/hec-vs-ibcc/']),
 dict(slug='ibcc-attestation',symbol='IBCC',title='IBCC Attestation Assistance',desc='Find the right starting point for school certificates, diplomas and board-issued records.',audience='Applicants with school-level qualifications or a diploma whose attesting authority needs to be identified.',answer='The awarding body and qualification level matter. Check IBCC’s scope before treating a diploma or school certificate as a university qualification.',steps=['Identify the board or awarding body and the exact certificate title.','Ask the issuer about verification and correction of record differences.','Confirm IBCC eligibility, prerequisites and the permitted submission route.','Check destination requirements after the educational stage.'],check='Not every document called a diploma follows the same route. Technical and vocational certificates may involve a different competent authority.',sources=['ibcc','navttc'],related=['/documents/education/','/guides/hec-vs-ibcc/','/navttc/']),
 dict(slug='mofa-attestation',symbol='MOFA',title='MOFA Attestation Assistance',desc='Understand document-specific prerequisites before the foreign affairs stage.',audience='People preparing Pakistani documents for a receiving organisation abroad.',answer='Check the document category and prerequisite signatures before approaching MOFA. Do not assume that every document can be submitted in the same way.',steps=['Identify the original issuer and any prior authority stage.','Check the latest MOFA instructions for this document category.','Confirm identity, representation and appearance requirements.','Confirm whether the destination needs an apostille or another legalization route.'],check='Fees, appointment arrangements, courier eligibility and personal appearance rules can change. Confirm them directly before payment or travel.',sources=['mofa'],related=['/guides/mofa-attestation-pakistan/','/services/apostille/','/services/embassy-legalization/']),
 dict(slug='apostille',symbol='A /',title='Apostille Assistance',desc='Check whether the Convention route applies to your document and destination.',audience='Applicants whose receiving organisation requests an apostille on a Pakistani public document.',answer='An apostille route depends on the Convention being applicable between the relevant states, the document being within its scope and the receiving organisation’s requirements. Country membership alone is not the complete check.',steps=['Obtain the receiving organisation’s written instructions.','Check the HCCH status table, entry into force and relevant declarations or objections.','Confirm the document category and prerequisites with the competent authority.','Check translation and recognition requirements separately.'],check='An apostille authenticates origin; it does not establish that a qualification will be recognised or that the document’s contents will be accepted.',sources=['hcch','mofa'],related=['/guides/apostille-vs-embassy-attestation/','/countries/','/services/mofa-attestation/']),
 dict(slug='embassy-legalization',symbol='↗',title='Embassy Legalization Assistance',desc='Make sense of consular stages and destination-specific requirements.',audience='Customers whose receiving authority asks for consular or embassy legalization.',answer='Ask the relevant embassy or consulate which process applies to the specific document and intended use. A route used for one destination or document may not apply to another.',steps=['Confirm the receiving institution and exact purpose.','Check the relevant embassy’s current document instructions.','Identify preceding verification and authentication stages.','Confirm translation, appointment and any destination-side stage.'],check='Do not assume embassy legalization is always needed in addition to an apostille. Establish the applicable route before paying for either.',sources=['mofa','hcch'],related=['/countries/uae/','/countries/saudi-arabia/','/guides/apostille-vs-embassy-attestation/']),
 dict(slug='super-legalization',symbol='02 /',title='Super Legalization Assistance',desc='Clarify additional authentication requested after an earlier legalization stage.',audience='Applicants asked for another legalization or verification after obtaining a stamp or certificate.',answer='“Super legalization” can be used differently by different organisations. Ask who requires the additional stage and exactly which previous signature or document must be authenticated.',steps=['Collect the written request for the extra stage.','Identify who issued the existing authentication.','Confirm the competent embassy or destination authority.','Check whether originals, translations or a new submission are needed.'],check='An additional stamp is not automatically required. We help clarify the request, without guaranteeing acceptance or recommending unnecessary stages.',sources=['mofa'],related=['/services/embassy-legalization/','/problems/document-rejected/','/contact/']),
]
GUIDES = [
 dict(slug='degree-name-different-from-passport',title='Degree name different from passport?',category='Document problems',desc='Identify which record needs attention before starting attestation.',answer='Compare the degree, passport and identity record. Ask the institution responsible for the incorrect record about its correction process. Do not edit the document yourself or assume an affidavit will be accepted.',sections=[('Why the distinction matters','A missing surname, transliteration difference or changed name may need a different response. The spelling that appears most often is not, by itself, proof that a record is correct.'),('A practical sequence','Record the exact difference. Identify the issuer of each document. Ask the receiving institution what evidence it will accept. Then obtain written correction or verification instructions from the relevant issuer.'),('Documents to have available','Keep your degree, transcript, passport, identity record and the receiving organisation’s request available for your own comparison. At the first enquiry, describe the difference without sending document numbers or scans.'),('Common problems','Avoid handwritten changes, unverified agents promising a new stamp, and assuming that a “one and the same person” affidavit is universally sufficient.'),('What varies','University correction procedures, identity record changes and acceptance by a foreign institution are separate decisions. Passport enquiries belong with DGIP; identity record enquiries belong with NADRA.')],sources=['hec','dgip','nadra'],related=['/problems/name-mismatch/','/documents/degree/','/services/hec-attestation/']),
 dict(slug='mofa-attestation-pakistan',title='MOFA attestation in Pakistan: where to begin',category='Attestation essentials',desc='Start with the document category and the authority that comes before MOFA.',answer='Identify your document and its prerequisite verification before choosing a submission route. Check MOFA’s current instructions for that category rather than using a single checklist for every document.',sections=[('What the MOFA stage means','Foreign affairs authentication is part of a wider document journey. It does not replace checking the original record or establishing acceptance by the receiving organisation.'),('A practical sequence','Identify the issuer, establish any preceding educational or other authority stage, confirm current MOFA requirements, then confirm what the recipient needs after authentication.'),('Documents to have available','The exact document title, issuing authority, existing verification and written destination requirements are useful starting information. The official checklist determines which originals and supporting records to submit.'),('Common problems','Missing prerequisites, inconsistent identity details and using a submission route that is not permitted for the document can cause avoidable difficulties.'),('What varies','Official fees, permitted representation, appearance requirements, appointment arrangements and the destination route. Confirm these before travel or payment.')],sources=['mofa','hec','ibcc'],related=['/services/mofa-attestation/','/guides/apostille-vs-embassy-attestation/','/process/']),
 dict(slug='apostille-vs-embassy-attestation',title='Apostille or embassy legalization?',category='The right route',desc='The answer depends on more than a destination’s name.',answer='Establish whether the Apostille Convention applies to the document and between the relevant states. If it does not, ask the competent authorities about the applicable legalization route. Confirm the recipient’s instructions in either case.',sections=[('Two routes, one initial question','Start with who is receiving the document and why. A university, employer, court or public office may have additional requirements beyond authentication.'),('A practical sequence','Identify the country of issue and destination. Check the HCCH status table and relevant declarations. Ask the competent authority about the document’s scope. Obtain the receiving organisation’s written instructions.'),('Documents to have available','The document category, issuing country, destination and the recipient’s request. Check whether a translation, a copy or the original is requested.'),('Common problems','Country membership alone does not resolve treaty applicability. Entry-into-force dates, objections, document exclusions and the intended use may matter.'),('What varies','Translation, professional recognition, equivalence and destination-side procedures are separate questions. Do not treat a stamp as a guarantee that all of them are satisfied.')],sources=['hcch','mofa'],related=['/services/apostille/','/services/embassy-legalization/','/countries/']),
 dict(slug='hec-vs-ibcc',title='HEC or IBCC: which authority should you check?',category='Education',desc='Look at the qualification and awarding body, not just the word “certificate”.',answer='HEC’s attestation service concerns eligible higher-education documents. For school-level qualifications, check IBCC’s scope and requirements. Technical qualifications and diplomas need a closer look at their issuer and level.',sections=[('Why the issuer matters','A university transcript, school certificate and vocational certificate can all describe education, but they are not interchangeable for attestation.'),('A practical sequence','Write down the exact qualification, awarding body and campus. Check the relevant authority’s scope. Identify prerequisites and only then select a submission route.'),('Documents to have available','Your qualification title, transcript or marks record, awarding institution and existing verification details. Use the authority’s current checklist for submission documents.'),('Common problems','Assuming every diploma goes through IBCC or every certificate goes through HEC can send a file to the wrong place.'),('What varies','Equivalence, recognition and attestation are distinct processes. A foreign qualification or technical certificate may need a different enquiry.')],sources=['hec','ibcc','navttc'],related=['/services/hec-attestation/','/services/ibcc-attestation/','/navttc/']),
 dict(slug='why-documents-get-rejected',title='Why was your document rejected?',category='Problem solving',desc='Use the stated reason to decide the next step.',answer='Keep the rejection or query notice. Identify whether the issue concerns the record, missing supporting material, eligibility or submission method before attempting another application.',sections=[('Start with the actual notice','A rejection does not always mean the underlying document is invalid. Read the authority’s explanation and distinguish a request for information from a final decision.'),('A practical sequence','Save the notice and reference privately. Identify each requested change. Ask the responsible authority for clarification where needed. Resolve the issue through that authority before resubmitting.'),('Documents to have available','The query wording, document category and a list of what was submitted. Remove personal identifiers when describing the issue in an initial email.'),('Common problems','Resubmitting the same file without addressing the reason, changing the wrong record or buying an additional attestation that does not answer the query.'),('What varies','Review, correction, appeal and reapplication procedures belong to the deciding authority. Do not assume one authority’s procedure applies to another.')],sources=['hec','ibcc','mofa'],related=['/problems/document-rejected/','/problems/missing-document/','/contact/']),
]
DOCUMENTS = [
 dict(slug='education',title='Educational documents',desc='Degrees, diplomas, transcripts and certificates each begin with the right issuer.',answer='Identify the qualification level and awarding body first. University, school and vocational records may follow different verification paths.',sections=[('Start with the qualification','Write down the document title, awarding institution and level. A diploma alone does not identify an attesting authority.'),('What to check together','Compare names, programme titles, dates and institution details across the certificate and supporting academic record.'),('Your next step','Check HEC for eligible higher-education records, IBCC for relevant school qualifications, or the competent vocational authority for technical records.')],sources=['hec','ibcc','navttc'],related=['/documents/degree/','/services/hec-attestation/','/services/ibcc-attestation/']),
 dict(slug='degree',title='University degree assistance',desc='A clear starting point for your degree, transcript and international plans.',answer='Begin with the issuing university, the academic record and HEC’s current eligibility and application requirements. Confirm the receiving institution’s requirements separately.',sections=[('Check the record first','Compare your degree, transcript and identity details. Ask the university about any difference in the academic record before proceeding.'),('Employment and study are different uses','An employer may request authentication, while a university or evaluation organisation may require records sent by a particular method. Obtain the recipient’s instructions.'),('Before submission','Check the current official checklist and whether your qualification or institution needs a separate recognition or equivalence enquiry.')],sources=['hec'],related=['/services/hec-attestation/','/guides/degree-name-different-from-passport/','/countries/uae/']),
 dict(slug='personal',title='Personal documents',desc='Guidance for birth, marriage, police and family records.',answer='The correct starting point depends on the exact record and who issued it. Civil registration, identity records and police certificates should not be treated as a single document category.',sections=[('Identify the precise document','Distinguish a marriage registration certificate from a marriage contract, a birth record from an identity document, and a police certificate from other character references.'),('Compare identity details','Check names and dates against the supporting records. Corrections must come through the responsible issuer.'),('Ask the recipient','Confirm the document format, any freshness requirement and whether translations or further authentication are requested.')],sources=['mofa','nadra'],related=['/documents/marriage-certificate/','/services/mofa-attestation/','/problems/name-mismatch/']),
 dict(slug='marriage-certificate',title='Marriage certificate assistance',desc='Identify the marriage record and the requirements of the organisation receiving it.',answer='Confirm exactly which marriage record is requested and which authority issued yours. A marriage contract, registration certificate and translation serve different purposes.',sections=[('Which record do you have?','Start with the document’s title and issuing body. Do not assume that a translation replaces the underlying record.'),('What to compare','Review both spouses’ names, identity details and the registration information. Ask the issuer about discrepancies.'),('Before international use','Obtain the recipient’s written instructions for originals, translations and authentication. The purpose may be family residence, marriage recognition or another process.')],sources=['mofa','nadra'],related=['/documents/personal/','/services/embassy-legalization/','/problems/name-mismatch/']),
 dict(slug='business',title='Commercial and legal documents',desc='Understand the document, signatory and intended use before arranging authentication.',answer='Identify whether the file is a corporate record, commercial instrument, agreement or power of attorney. Each can involve different issuing, witnessing and appearance requirements.',sections=[('Document and signatory','Record who issued or signed the instrument, their capacity and the organisation requesting it. Avoid sending confidential commercial terms in an initial enquiry.'),('Confirm the competent route','Ask the relevant authority whether a chamber, notary, registrar or other institution has a role. Do not assume these are interchangeable.'),('Powers of attorney','Execution, identity verification and personal appearance can be material. Obtain instructions from the competent authority and seek qualified legal advice on the instrument’s legal effect.')],sources=['mofa'],related=['/services/mofa-attestation/','/services/embassy-legalization/','/contact/']),
 dict(slug='international-use',title='Documents for international use',desc='Connect the document you have with the destination and purpose.',answer='Start with the organisation receiving your document. Authentication, translation and recognition are separate requirements, and not every document needs the same route.',sections=[('Ask for written requirements','Identify whether the recipient needs an original, certified copy, translation or direct verification from the issuer.'),('Establish the authentication route','Check Convention applicability for an apostille, or confirm the relevant embassy legalization route. Do not automatically purchase both.'),('Keep the purpose visible','Employment, study, immigration and business applications can use the same document in different ways. The purpose belongs in your assessment.')],sources=['hcch','mofa'],related=['/countries/','/services/apostille/','/guides/apostille-vs-embassy-attestation/']),
]
PROBLEMS = [
 ('name-mismatch','Name doesn’t match','Passport ≠ Degree','Compare the actual records and identify the institution responsible for the difference. Do not change a document yourself.','Write down the exact spelling on each record. Ask the receiving organisation what evidence it needs and the relevant issuer how to correct or verify the record.','degree-name-different-from-passport'),
 ('document-rejected','Document rejected','Something is missing','Use the authority’s stated reason as the starting point. Repeating a submission without addressing the query may not resolve it.','Save the notice, identify the requested change and ask the deciding authority about its correction or review process. Describe the issue without sharing a case number in the first enquiry.','why-documents-get-rejected'),
 ('which-authority','Not sure which authority','HEC? IBCC? MOFA?','The document’s issuer and qualification level determine which authority to check first. The name of the document alone may be insufficient.','Identify the exact issuer, document title and purpose. Separate verification of the original record from subsequent authentication.','hec-vs-ibcc'),
 ('apostille-or-embassy','Apostille or embassy?','Which route applies?','Check treaty applicability and the receiving organisation’s instructions before choosing an authentication route.','Confirm issuing country, destination, document category and intended use. Check the official Convention status and relevant declarations.','apostille-vs-embassy-attestation'),
 ('missing-document','Missing document','What do you need first?','Find out whether the missing item is an original record, supporting evidence or an earlier verification. These need different next steps.','Compare the official checklist with what you have. Ask the issuer about replacement records and the receiving authority whether any alternative is permitted.','why-documents-get-rejected'),
 ('previously-rejected','Previously rejected','Understand before resubmitting','A previous rejection needs a review of the reason and what has changed. Additional stamps alone may not address the issue.','Keep the original notice and list the actions taken since. Ask the deciding authority to clarify unresolved points before starting another application.','why-documents-get-rejected'),
]
COUNTRIES = {
 'UAE': 'For use in the UAE, establish what the receiving organisation needs and check UAE MOFA’s attestation instructions. Ask about any destination-side stage and translations before choosing a route.',
 'Saudi Arabia': 'For Saudi Arabia, identify whether the request concerns employment, academic recognition or a technical trade. Check the receiving body’s instructions; do not assume every document follows the same consular route.',
 'Qatar': 'For Qatar, obtain the requesting organisation’s checklist and confirm the competent consular route. The document category, purpose and any translation request matter.',
 'Oman': 'For Oman, check Convention applicability as well as the recipient’s requirements. An authentication route does not settle recognition or translation requirements.',
 'Bahrain': 'For Bahrain, check the relevant treaty relationship and the document’s scope. Confirm with the receiving institution before arranging additional legalization.',
 'Kuwait': 'For Kuwait, ask the relevant embassy and recipient about the applicable authentication stages. Check whether the request is for the original, a copy or a translation.',
 'UK': 'For the UK, establish whether the recipient needs authentication, direct issuer verification or a different form of evidence. Confirm Convention applicability where an apostille is requested.',
 'Germany': 'For Germany, review relevant Convention declarations and the German recipient’s instructions. Confirm translation and recognition requirements separately.',
 'France': 'For France, ask the recipient which form of the document it accepts and whether a translation is needed. Verify the applicable authentication route before submission.',
 'Italy': 'For Italy, establish whether the request concerns document authentication, academic recognition or both. Confirm the receiving institution’s requirements for translations.',
 'Canada': 'For Canada, distinguish an apostille request from credential evaluation or direct academic verification. Check the particular receiving organisation’s instructions.',
 'Australia': 'For Australia, ask whether the recipient needs an original, certified copy or issuer verification. Authentication and professional or academic recognition are separate checks.',
 'USA': 'For the USA, identify the specific receiving institution and its document rules. An employer, university and licensing board may ask for different evidence.',
 'Europe': 'Europe is not a single document jurisdiction. Identify the specific country and receiving organisation before checking the authentication route.',
 'Other': 'Start with the exact destination country and receiving organisation. We can help identify which official instructions to check for your document and purpose.'
}
FAQS = [
 ('Government','Are you a government authority?','No. SK Attestations provides independent private assistance. HEC, IBCC, MOFA, embassies and other competent authorities make their own official decisions.'),
 ('Government','Can you guarantee an attestation?','No. Eligibility, approval and acceptance belong to the relevant authorities and receiving organisations. We can help you understand and prepare for the process.'),
 ('Documents','Can someone submit on my behalf?','Representation, personal appearance and courier rules vary by authority and document. Check the current official instructions before authorising anyone or sending originals.'),
 ('Documents','Should I upload my documents here?','No. This website has no document upload. Start with the document type, destination, purpose and a description of the issue. Do not send identity numbers or scans in the initial enquiry.'),
 ('Apostille','Does an apostille work for every country?','No. Check the Convention relationship, document scope and relevant declarations, as well as the receiving organisation’s requirements. Country membership alone is not a complete assessment.'),
 ('Embassy','Do I need both an apostille and embassy legalization?','Do not assume both are needed. Establish which route applies to the specific document and purpose, and confirm it with the competent authority.'),
 ('Problems','What if my degree and passport names differ?','Compare the records and contact the responsible issuer about correction or verification. Do not physically alter the document or assume an affidavit will be accepted.'),
 ('Countries','Are requirements the same for every destination?','No. They vary by destination, receiving organisation, document and purpose. Obtain written instructions from the organisation that will use the document.'),
 ('NAVTTC','Do you conduct NAVTTC tests?','No. We provide independent test booking and technical document guidance. Official centres and programme authorities control eligibility, testing, availability and outcomes.'),
]
